config/routes.rb
Rails.application.routes.draw do
  get 'course_instructors/new'

  get 'ctemps/new'

  get 'coursetemp/new'

  get 'instructor_sessions/new'

  get 'instructors/new'

  get 'student_sessions/new'

  get 'students/new'

  get 'sessions/new'

  get 'admins/new'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'admins#new'
  get 'signup_student'  => 'students#new'
  get 'signup_instructor'  => 'instructors#new'
  get 'signup_course'  => 'courses#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get    'student_login'   => 'student_sessions#new'
  post   'student_login'   => 'student_sessions#create'
  delete 'student_logout'  => 'student_sessions#destroy'
  get    'instructor_login'   => 'instructor_sessions#new'
  post   'instructor_login'   => 'instructor_sessions#create'
  delete 'instructor_logout'  => 'instructor_sessions#destroy'
  
  get 'history'  => 'students#history'
  get 'student_enrollment'  => 'students#enrollment'
  get 'course_view'  => 'students#course_view'
  get 'search'  => 'students#search'
  get 'student_courseinfo' => 'students#courseinfo'
  get 'enroll'  => 'students#enroll'
  delete 'drop_course'  => 'students#drop_course'
  
  get 'req'  => 'instructors#req'
  get 'instructor_courseinfo' => 'instructors#courseinfo'
  get 'studentsincourse_info' => 'instructors#studentsincourseinfo'
  get 'approve'   => 'instructors#approve'
  get 'grade'   => 'instructors#grade'
  get 'grade_student'   => 'instructors#gradestudent'
  delete 'remove_student'   => 'instructors#removestudent'
  delete 'disapprove'   => 'instructors#disapprove'
  

  get 'add_student'  => 'courses#add_student'
  get 'drop_student'  => 'courses#drop_student'
  get 'add_instructor'  => 'courses#add_instructor'
  get 'drop_instructor'  => 'courses#drop_instructor'
  get 'coursematerial_info' => 'courses#coursematerialinfo'
  get 'addmaterial'   => 'courses#addmaterial'
  
  get 'adminsaddmaterial'   => 'admins#addmaterial'
  get 'admin_grade'   => 'admins#admingrade'
  get 'admin_grade_student'   => 'admins#gradestudent'
  get 'studenthistroy'   => 'admins#studenthistroy'
  
  resources :admins
  resources :students
  resources :instructors
  resources :courses
  resources :ctemps
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      redirect_to current_admin
    elsif student_logged_in?
      redirect_to current_student
    elsif instructor_logged_in?
      redirect_to current_instructor
    end
  end

  def help
  end
  
  def about
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  This is the project 1, ruby on rails.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Song Ju, sju2@ncsu.edu
</p>
<p>
    Hui Guan, hguan2@ncsu.edu
</p>
<p>
    Yiqiao Xu, yxu35@ncsu.edu
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://www.railstutorial.org/#help">Rails Tutorial help section</a>.
  To get help on this sample app, see the
  <a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
  book</a>.
</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="center jumbotron">
  <h1>Welcome to the Class Portal</h1>
  
<br/>

  <%= link_to "Admin!", login_path, class: "btn btn-lg btn-primary" %>
  
  <%= link_to "Student!", student_login_path, class: "btn btn-lg btn-primary" %>
  
  <%= link_to "Instructor!", instructor_login_path, class: "btn btn-lg btn-primary" %>
  
</div>