config/routes.rb
Rails.application.routes.draw do
  get 'course_instructors/new'

  get 'ctemps/new'

  get 'coursetemp/new'

  get 'instructor_sessions/new'

  get 'instructors/new'

  get 'student_sessions/new'

  get 'students/new'

  get 'sessions/new'

  get 'admins/new'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'admins#new'
  get 'signup_student'  => 'students#new'
  get 'signup_instructor'  => 'instructors#new'
  get 'signup_course'  => 'courses#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get    'student_login'   => 'student_sessions#new'
  post   'student_login'   => 'student_sessions#create'
  delete 'student_logout'  => 'student_sessions#destroy'
  get    'instructor_login'   => 'instructor_sessions#new'
  post   'instructor_login'   => 'instructor_sessions#create'
  delete 'instructor_logout'  => 'instructor_sessions#destroy'
  
  get 'history'  => 'students#history'
  get 'student_enrollment'  => 'students#enrollment'
  get 'course_view'  => 'students#course_view'
  get 'search'  => 'students#search'
  get 'student_courseinfo' => 'students#courseinfo'
  get 'enroll'  => 'students#enroll'
  delete 'drop_course'  => 'students#drop_course'
  
  get 'req'  => 'instructors#req'
  get 'instructor_courseinfo' => 'instructors#courseinfo'
  get 'studentsincourse_info' => 'instructors#studentsincourseinfo'
  get 'approve'   => 'instructors#approve'
  get 'grade'   => 'instructors#grade'
  get 'grade_student'   => 'instructors#gradestudent'
  delete 'remove_student'   => 'instructors#removestudent'
  delete 'disapprove'   => 'instructors#disapprove'
  

  get 'add_student'  => 'courses#add_student'
  get 'drop_student'  => 'courses#drop_student'
  get 'add_instructor'  => 'courses#add_instructor'
  get 'drop_instructor'  => 'courses#drop_instructor'
  get 'coursematerial_info' => 'courses#coursematerialinfo'
  get 'addmaterial'   => 'courses#addmaterial'
  
  get 'adminsaddmaterial'   => 'admins#addmaterial'
  get 'admin_grade'   => 'admins#admingrade'
  get 'admin_grade_student'   => 'admins#gradestudent'
  get 'studenthistroy'   => 'admins#studenthistroy'
  
  resources :admins
  resources :students
  resources :instructors
  resources :courses
  resources :ctemps
  
end

app/models/student.rb
class Student < ActiveRecord::Base
    
    attr_accessor :remember_token
    before_save { self.email = email.downcase }
    validates :name,  presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
    has_many :enrollments
    has_many :courses, through: :enrollments
    
    # 返回指定字符串的哈希摘要
  def Student.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  # 返回一个随机令牌
  def Student.new_token
    SecureRandom.urlsafe_base64
  end
  
  # 为了持久会话，在数据库中记住用户
  def remember
    self.remember_token = Student.new_token
    update_attribute(:remember_digest, Student.digest(remember_token))
  end
  
  # 如果指定的令牌和摘要匹配，返回 true
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  # 忘记用户
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  
  def index
    @students = Student.paginate(page: params[:page])
  end
  
  def show
    @student = Student.find(params[:id])
  end
  
  def new
    @student = Student.new
  end
  
  def create
    @student = Student.new(student_params)
    if @student.save
      student_log_in @student
      flash[:success] = "Welcome to the Class Portal!"
      redirect_to @student
    else
      render 'new'
    end
  end
  
  def edit
    @student = Student.find(params[:id])
  end
  
  def update
    @student = Student.find(params[:id])
    if @student.update_attributes(student_params)
      flash[:success] = "Profile updated"
      redirect_to @student
    else
      render 'edit'
    end
  end
  
  def destroy
    Student.find(params[:id]).destroy
    flash[:success] = "Student deleted"
    redirect_to students_url
  end
  
  def history
    @student = current_student
    @enrollments = Enrollment.where(status: true, student_email: @student.email)
    @enrollments_pending = Enrollment.where(status: false, student_email: @student.email)
  end
  
  def search
    if params[:search]
        @courses = Course.search(params[:search], params[:searchby])
      if !@courses.is_a? Array
          @courses.order("course_number ASC")
        else
          @courses.sort!{|a,b| a.course_number <=> b.course_number}
      end
    else
        @courses = Course.all.order('course_number ASC')
    end
  end
  
  def results
    @courses = Enrollment.where(course_number: @course.course_number)
  end
  
  def enroll
    @student = current_student
    course_number = params[:course_number]
    if Enrollment.find_by(course_number: course_number, student_email: @student.email)
      flash[:success] = "Has already enrolled"
    else
      Enrollment.create(course_number: course_number, student_email: @student.email, status: 0)
      flash[:success] = "Enroll succeed"
    end
    redirect_to search_url
  end
  
  def drop_course
    Enrollment.find(params[:enrollment_id]).destroy
    flash[:success] = "Drop succeed!"
    redirect_to history_url
  end
  
  def courseinfo
    @course = Course.find(params[:course_id])
  end

  private

    def student_params
      params.require(:student).permit(:name, :email, :password,
                                   :password_confirmation)
    end
    def student_enrollment_params
     params.require(:enrollment).permit(:course_number, :student_email, :status => false)
    end
    
    
  # 确保是正确的用户
    def correct_student
      @student = Student.find(params[:id])
      redirect_to(root_url) unless current_student?(@student)
    end

end

app/helpers/students_helper.rb
module StudentsHelper
     # 返回指定用户的 Gravatar
  def gravatar_for(student)
    gravatar_id = Digest::MD5::hexdigest(student.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: student.name, class: "gravatar")
  end
end

app/views/students/_student.html.erb
<li>
      <%= gravatar_for student%>
      <%= link_to student.name, student %>
      | <%= link_to "histroy", studenthistroy_path(student_id: student.id)%>
      | <%= link_to "delete", student, method: :delete, data: { confirm: "You sure?" } %>
</li>

app/views/students/courseinfo.html.erb
<% provide(:title, @course.course_number) %>
<div class="row">

    <section class="course_info">
        
      <h1><%= @course.course_number %></h1>
      
      <h2>Title: <%= @course.title %></h2>
      
      <h2>Description: <%= @course.description %></h2>
      
      <h2>Instructor: 
            <% @courseinstructors = CourseInstructor.all%>
                  <% @courseinstructors.each do |instructor| %>
                    <% if instructor.course_number == @course.course_number %>
                            <% @instruct = Instructor.find_by(email: instructor.instructor_email) %>
                            <%= @instruct.name %>;
                    <% end %>
                  <% end %>
      </h2>
      
      <h2>Start_date: <%= @course.start_date %></h2>
      
      <h2>End_date: <%= @course.end_date %></h2>
      
      <h2>Status: <%= @course.status %></h2>
      
      <h1>Materials of <%= @course.course_number %></h1>
      
      <% @materials = CourseMaterial.where(course_number: @course.course_number ) %>
        <% @materials.each do |m| %>
            
                <li>
                    <%= m.material%>
                </li>
            
            <hr style=" height:2px;border:none;border-top:2px dotted #185598;" />
        <% end %>
        
      <%if @course.status == "Active" %>
      <h2><%= link_to "Enroll", enroll_path(course_number: @course.course_number), class: "btn btn-primary btn-block" %></h2>
      <% end %>
      
    </section>
    
    
</div>

app/views/students/edit.html.erb
<% provide(:title, "Edit student") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@student) do |f| %>
      <%= render 'shared/student_error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @student %>
      <a href="http://gravatar.com/emails" target="_blank">change</a>
    </div>
  </div>
</div>

app/views/students/history.html.erb
<% provide(:title, 'All enrollments') %>
<h1>Enrollments</h1>

<ul class="courses">
  <% @enrollments.each do |enrollments| %>
    <li>
      <%= enrollments.course_number %>-----
      <%if enrollments.grade == nil %>
         no grade 
      <% else %>
        grade: <%= enrollments.grade %>
      <% end %>
      | <%= link_to "drop", drop_course_path(enrollment_id: enrollments.id), method: :delete, data: { confirm: "You sure?" } %>
    </li>
  <% end %>
</ul>

<hr style="height:1px;border:none;border-top:1px solid #555555;" />

<h1>Pendings</h1>

<ul class="courses">
  <% @enrollments_pending.each do |enrollments| %>
    <li>
      <%= enrollments.course_number %>
      | <%= link_to "drop", drop_course_path(enrollment_id: enrollments.id), method: :delete, data: { confirm: "You sure?" } %>
      
    </li>
  <% end %>
</ul>

app/views/students/index.html.erb
<% provide(:title, 'All students') %>
<h1>All students</h1>

<%= will_paginate %>

<ul class="students">
      <%= render @students %>
</ul>

<%= will_paginate %>

app/views/students/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@student) do |f| %>
      <%= render 'shared/student_error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create student account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/students/results.html.erb
<% provide(:title, "Search course") %>
<h1>Search courses</h1>

<ul class="courses">
  <div>
  <% @courses.each do |course| %>
    <li>
      <%= course.course_number %>
      | <%= link_to "view", courses_path %>
      
    </li>
  <% end %>
  </div>
</ul>

app/views/students/search.html.erb
<% provide(:title, 'All enrollments') %>
<h1>Search for class</h1>

<div class="row">
    
    <%= form_tag(search_path, :method => "get", id: "search-form") do %>
    <div class="col-xs-6">
        <%= text_field_tag :search, params[:search], placeholder: "Search Courses", class:'form-control' %>
    </div>
    
    <div class="col-xs-3">
        <select id="searchby" name="searchby" class="form-control">
            <option>Course number</option>
            <option>Title</option>
            <option>Instructor</option>
            <option>Description</option>
            <option>Status</option>
        </select>
    </div>
    <div class="col-xs-3">
        <%= submit_tag "Search", class:'btn btn-primary' %>
    </div>
    <% end %>
</div>


<ul class="courses">
  <% @courses.each do |course| %>
    <li>
      <%= link_to course.course_number , student_courseinfo_path(course_id: course.id) %>
    </li>
  <% end %>
</ul>

app/views/students/show.html.erb
<% provide(:title, @student.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="student_info">
      <h1>
        <%= gravatar_for @student %>
        <%= @student.name %>
      </h1>
      <h2>Email: <%= @student.email %></h2>
    </section>
  </aside>
</div>