config/routes.rb
Rails.application.routes.draw do
  get 'course_instructors/new'

  get 'ctemps/new'

  get 'coursetemp/new'

  get 'instructor_sessions/new'

  get 'instructors/new'

  get 'student_sessions/new'

  get 'students/new'

  get 'sessions/new'

  get 'admins/new'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'admins#new'
  get 'signup_student'  => 'students#new'
  get 'signup_instructor'  => 'instructors#new'
  get 'signup_course'  => 'courses#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get    'student_login'   => 'student_sessions#new'
  post   'student_login'   => 'student_sessions#create'
  delete 'student_logout'  => 'student_sessions#destroy'
  get    'instructor_login'   => 'instructor_sessions#new'
  post   'instructor_login'   => 'instructor_sessions#create'
  delete 'instructor_logout'  => 'instructor_sessions#destroy'
  
  get 'history'  => 'students#history'
  get 'student_enrollment'  => 'students#enrollment'
  get 'course_view'  => 'students#course_view'
  get 'search'  => 'students#search'
  get 'student_courseinfo' => 'students#courseinfo'
  get 'enroll'  => 'students#enroll'
  delete 'drop_course'  => 'students#drop_course'
  
  get 'req'  => 'instructors#req'
  get 'instructor_courseinfo' => 'instructors#courseinfo'
  get 'studentsincourse_info' => 'instructors#studentsincourseinfo'
  get 'approve'   => 'instructors#approve'
  get 'grade'   => 'instructors#grade'
  get 'grade_student'   => 'instructors#gradestudent'
  delete 'remove_student'   => 'instructors#removestudent'
  delete 'disapprove'   => 'instructors#disapprove'
  

  get 'add_student'  => 'courses#add_student'
  get 'drop_student'  => 'courses#drop_student'
  get 'add_instructor'  => 'courses#add_instructor'
  get 'drop_instructor'  => 'courses#drop_instructor'
  get 'coursematerial_info' => 'courses#coursematerialinfo'
  get 'addmaterial'   => 'courses#addmaterial'
  
  get 'adminsaddmaterial'   => 'admins#addmaterial'
  get 'admin_grade'   => 'admins#admingrade'
  get 'admin_grade_student'   => 'admins#gradestudent'
  get 'studenthistroy'   => 'admins#studenthistroy'
  
  resources :admins
  resources :students
  resources :instructors
  resources :courses
  resources :ctemps
  
end

app/models/instructor.rb
class Instructor < ActiveRecord::Base
  
    has_many :course_instructors
    
    attr_accessor :remember_token
    before_save { self.email = email.downcase }
    validates :name,  presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
    
    # 返回指定字符串的哈希摘要
  def Instructor.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  # 返回一个随机令牌
  def Instructor.new_token
    SecureRandom.urlsafe_base64
  end
  
  # 为了持久会话，在数据库中记住用户
  def remember
    self.remember_token = Instructor.new_token
    update_attribute(:remember_digest, Instructor.digest(remember_token))
  end
  
  # 如果指定的令牌和摘要匹配，返回 true
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  # 忘记用户
  def forget
    update_attribute(:remember_digest, nil)
  end
  
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  
  def index
    @instructors = Instructor.paginate(page: params[:page])
  end
  
  def show
    @instructor = Instructor.find(params[:id])
  end
  
  def new
    @instructor = Instructor.new
  end
  
  def create
    @instructor = Instructor.new(instructor_params)
    if @instructor.save
      flash[:success] = "Success!"
      redirect_to @instructor
    else
      render 'new'
    end
  end
  
  def edit
    @instructor = Instructor.find(params[:id])
  end
  
  def update
    @instructor = Instructor.find(params[:id])
    if @instructor.update_attributes(instructor_params)
      flash[:success] = "Profile updated"
      redirect_to @instructor
    else
      render 'edit'
    end
  end
  
  def destroy
    Instructor.find(params[:id]).destroy
    flash[:success] = "Instructor deleted"
    redirect_to instructors_url
  end
  
  def req
    @instructor = current_instructor
    @enrollments = Enrollment.where(status: false )
  end
  
  def studentsincourseinfo
    @course = Course.find_by(course_number: params[:course_number])
    @enrollments = Enrollment.where(course_number: params[:course_number], status: true)
  end
  
  def courseinfo
    @instructor = current_instructor
    @Course_Instructor_infos = CourseInstructor.where(instructor_email: @instructor.email)
  end
  
  def grade
    @enrollment = Enrollment.find(params[:enrollment_id])
    @student = Student.find_by(email: @enrollment.student_email)
  end
  
  def gradestudent
    @enrollment = Enrollment.find(params[:enroll_id])
    s_grade = params[:grade]
    @enrollment.update_attributes(grade: s_grade)
    redirect_to studentsincourse_info_path(course_number: @enrollment.course_number)
  end
  
  def removestudent
    @enrollment = Enrollment.find(params[:enrollment_id])
    Enrollment.find(params[:enrollment_id]).destroy
    flash[:success] = "Remove succeed!"
    redirect_to studentsincourse_info_path(course_number: @enrollment.course_number)
  end
  
  def approve
    @enrollments = Enrollment.find_by(id: params[:request_id])
    @enrollments.update_attributes(status: 1)
    flash[:success] = "Enrollment approved"
    redirect_to req_url
  end
  
  def disapprove
    Enrollment.find(params[:request_id]).destroy
    flash[:success] = "Enrollment disapproved!"
    redirect_to req_url
  end
  
  private

    def instructor_params
      params.require(:instructor).permit(:name, :email, :password,
                                   :password_confirmation)
    end
    
    
  # 确保是正确的用户
    def correct_instructor
      @instructor = Instructor.find(params[:id])
      redirect_to(root_url) unless current_instructor?(@instructor)
    end
end

app/helpers/instructors_helper.rb
module InstructorsHelper
         # 返回指定用户的 Gravatar
  def gravatar_for(instructor)
    gravatar_id = Digest::MD5::hexdigest(instructor.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: instructor.name, class: "gravatar")
  end
end

app/views/instructors/courseinfo.html.erb
<% provide(:title, @instructor.name) %>


<% @Course_Instructor_infos.each do |t| %>
<% @course = Course.find_by(course_number: t.course_number) %>
<% if @course %>
    <div class="row">
    
        <section class="course_info">
            
          <h1><%= @course.course_number %></h1>
          
          <h2>Title: <%= @course.title %></h2>
          
          <h2>Description: <%= @course.description %></h2>
          
          <h2>Start_date: <%= @course.start_date %></h2>
          
          <h2>End_date: <%= @course.end_date %></h2>
          
          <h2>Status: <%= @course.status %></h2>
          
          <h2><%= link_to "Students", studentsincourse_info_path(course_number: @course.course_number), class: "btn btn-primary btn-lg" %>  <%= link_to "Material", coursematerial_info_path(course_number: @course.course_number), class: "btn btn-primary btn-lg" %></h2>
          
        </section>
        
    </div>
    
    <hr style="height:1px;border:none;border-top:1px solid #555555;" />
<% end %>
    
    
<% end %>

app/views/instructors/edit.html.erb
<% provide(:title, "Edit instructor") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@instructor) do |f| %>
      <%= render 'shared/instructor_error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @instructor %>
      <a href="http://gravatar.com/emails" target="_blank">change</a>
    </div>
  </div>
</div>

app/views/instructors/grade.html.erb
<% provide(:title, "Grade") %>

<h1><%= @enrollment.course_number %>:  grade for <%= @student.name %></h1>

<div class="row">

  <%= form_tag({ controller: 'instructors', action: 'gradestudent' }, method: 'get') do %>
    <%= label_tag(:q, "Grade") %>
    <%= text_field_tag :grade %>
    <%= hidden_field_tag :enroll_id, @enrollment.id %>
    <%= submit_tag "Grade", class: "btn btn-primary" %>
  <% end %>
  
</div>

app/views/instructors/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Create Instructor</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@instructor) do |f| %>
      <%= render 'shared/instructor_error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create an account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/instructors/req.html.erb
<% provide(:title, 'All enrollments') %>
<h1>All enrollments</h1>

<ul class="courses">
  <% @enrollments.each do |enrollment| %>
    <% if CourseInstructor.find_by(course_number: enrollment.course_number, instructor_email: @instructor.email) %>
    <li>
      <%= enrollment.course_number %>---------
      <%= enrollment.student_email %>
      <% @course = Course.find_by(course_number: enrollment.course_number) %>
      | <%= link_to "approve", approve_path(request_id: enrollment.id) %>
      | <%= link_to "disapprove", disapprove_path(request_id: enrollment.id), method: :delete, data: { confirm: "You sure?" } %>
    </li>
    <% end %>
  <% end %>
</ul>

app/views/instructors/show.html.erb
<% provide(:title, @instructor.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="instructor_info">
      <h1>
        <%= gravatar_for @instructor %>
        <%= @instructor.name %>
      </h1>
      <h2>Email: <%= @instructor.email %></h2>
    </section>
  </aside>
</div>

app/views/instructors/studentsincourseinfo.html.erb
<% provide(:title, @course.course_number) %>


<h1>Students----<%= @course.course_number %></h1>
    
    <ul class="courses">
      <% @enrollments.each do |enrollments| %>
        <% @student = Student.find_by(email: enrollments.student_email) %>
        <%if @student %>
        <li>

          Student: <%= @student.name %>-----
          <%if enrollments.grade == nil %>
             no grade 
          <% else %>
            grade: <%= enrollments.grade %>
          <% end %>
          <%if @course.status == "Active" %>
          | <%= link_to "grade", grade_path(enrollment_id: enrollments.id) %>
          | <%= link_to "remove", remove_student_path(enrollment_id: enrollments.id) ,method: :delete, data: { confirm: "You sure?" }%>
          <% end %>
        </li>
        <% end %>
      <% end %>
    </ul>
    