config/routes.rb
Rails.application.routes.draw do
  get 'course_instructors/new'

  get 'ctemps/new'

  get 'coursetemp/new'

  get 'instructor_sessions/new'

  get 'instructors/new'

  get 'student_sessions/new'

  get 'students/new'

  get 'sessions/new'

  get 'admins/new'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'admins#new'
  get 'signup_student'  => 'students#new'
  get 'signup_instructor'  => 'instructors#new'
  get 'signup_course'  => 'courses#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get    'student_login'   => 'student_sessions#new'
  post   'student_login'   => 'student_sessions#create'
  delete 'student_logout'  => 'student_sessions#destroy'
  get    'instructor_login'   => 'instructor_sessions#new'
  post   'instructor_login'   => 'instructor_sessions#create'
  delete 'instructor_logout'  => 'instructor_sessions#destroy'
  
  get 'history'  => 'students#history'
  get 'student_enrollment'  => 'students#enrollment'
  get 'course_view'  => 'students#course_view'
  get 'search'  => 'students#search'
  get 'student_courseinfo' => 'students#courseinfo'
  get 'enroll'  => 'students#enroll'
  delete 'drop_course'  => 'students#drop_course'
  
  get 'req'  => 'instructors#req'
  get 'instructor_courseinfo' => 'instructors#courseinfo'
  get 'studentsincourse_info' => 'instructors#studentsincourseinfo'
  get 'approve'   => 'instructors#approve'
  get 'grade'   => 'instructors#grade'
  get 'grade_student'   => 'instructors#gradestudent'
  delete 'remove_student'   => 'instructors#removestudent'
  delete 'disapprove'   => 'instructors#disapprove'
  

  get 'add_student'  => 'courses#add_student'
  get 'drop_student'  => 'courses#drop_student'
  get 'add_instructor'  => 'courses#add_instructor'
  get 'drop_instructor'  => 'courses#drop_instructor'
  get 'coursematerial_info' => 'courses#coursematerialinfo'
  get 'addmaterial'   => 'courses#addmaterial'
  
  get 'adminsaddmaterial'   => 'admins#addmaterial'
  get 'admin_grade'   => 'admins#admingrade'
  get 'admin_grade_student'   => 'admins#gradestudent'
  get 'studenthistroy'   => 'admins#studenthistroy'
  
  resources :admins
  resources :students
  resources :instructors
  resources :courses
  resources :ctemps
  
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  
  def new
      @course = Course.new
  end  

  def show
    @course = Course.find(params[:id])
  end
  
  def showcourse(cnum)
    @course = Course.find(cnum)
  end
  
  def create
    @course = Course.new(course_params)
    instructor_id = params[:instructor]
    @instructor = Instructor.find(instructor_id)
    @course.instructor = @instructor.email
    if @course.save
      CourseInstructor.create(course_number: @course.course_number, instructor_email: @instructor.email)
      redirect_to @course
    else
      render 'new'
    end
  end
  
  def edit
    @course = Course.find(params[:id])
  end
  
  def update
    @course = Course.find(params[:id])
    if @course.update_attributes(course_params)
      flash[:success] = "Course updated"
      redirect_to @course
    else
      render 'edit'
    end
  end
  
  def search
    @courses = Course.paginate(page: params[:page])
  end
  
  def index
    @courses = Course.paginate(page: params[:page])
  end
  
  def destroy
    Course.find(params[:id]).destroy
    flash[:success] = "Course deleted"
    redirect_to courses_url
  end
  
  
  def add_student
    @student = Student.find_by(id: params[:student])
    @course = Course.find_by(id: params[:course_id])
    if Enrollment.find_by(student_email: @student.email, course_number: @course.course_number)
        flash[:success] = "This student is already in class!"
    else
        Enrollment.create(course_number: @course.course_number, student_email: @student.email, status: 1)
        flash[:success] = "Add succeed"
    end
    redirect_to @course
  end
  
  def drop_student
    @enrollment = Enrollment.find_by(id: params[:request_id])
    @course = Course.find_by(course_number: @enrollment.course_number)
    Enrollment.find_by(id: params[:request_id]).destroy
    flash[:success] = "Drop succeed"
    redirect_to @course
  end
  
  def add_instructor
    @instructor = Instructor.find_by(id: params[:instructor])
    @course = Course.find_by(id: params[:course_id])
    if CourseInstructor.find_by(instructor_email: @instructor.email, course_number: @course.course_number)
        flash[:success] = "This instructor is already in class!"
    else
        CourseInstructor.create(course_number: @course.course_number, instructor_email: @instructor.email)
        flash[:success] = "Add succeed"
    end
    redirect_to @course
  end
  
  def drop_instructor
    @courseinstructor = CourseInstructor.find_by(id: params[:request_id])
    @course = Course.find_by(course_number: @courseinstructor.course_number)
    temp = @courseinstructor.course_number
    if CourseInstructor.where(course_number: temp).count ==1
        flash[:success] = "There must be at least one instructor in a class!"
    else
        CourseInstructor.find_by(id: params[:request_id]).destroy
        flash[:success] = "Drop succeed"
    end
    redirect_to @course
  end
  
  def coursematerialinfo
    @course = Course.find_by(course_number: params[:course_number])
    @materials = CourseMaterial.where(course_number: params[:course_number] )
  end
  
  def addmaterial
    content = params[:material]
    course_num = params[:course_number]
    CourseMaterial.create(course_number: course_num, material: content)
    flash[:success] = "Add material succeed!"
    redirect_to coursematerial_info_path(course_number: course_num)
  end
  
    private

    def course_params
      params.require(:course).permit(:course_number, :title, :description, :instructor, :start_date, :end_date, :status)
    end
    
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_course.html.erb
<li>
      <%= link_to course.course_number, course %>
</li>

app/views/courses/coursematerialinfo.html.erb
<% provide(:title, @course.course_number) %>

<h1><%= @course.course_number %>----Materials</h1>

<% @materials.each do |m| %>
    <div class="row">
        <li>
            <%= m.material%>
        </li>
    </div>
    <hr style=" height:2px;border:none;border-top:2px dotted #185598;" />
<% end %>

<div class="row">

<%if @course.status == "Active" %>
  <%= form_tag({ controller: 'courses', action: 'addmaterial' }, method: 'get') do %>
    <%= label_tag(:q, "Material") %>
    <%= text_area_tag( :material) %>
    <%= hidden_field_tag :course_number, @course.course_number %>
    <%= submit_tag "Add material", class: "btn btn-primary" %>
  <% end %>
<% end %>  
</div>

app/views/courses/edit.html.erb
<% provide(:title, "Edit course") %>
<h1>Edit course</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@course) do |f| %>
      <%= render 'shared/course_error_messages' %>

      <%= f.label :course_number %>
      <%= f.text_field :course_number, class: 'form-control' %>

      <%= f.label :Title %>
      <%= f.text_field :title, class: 'form-control' %>

      <%= f.label :Description %>
      <%= f.text_field :description, class: 'form-control' %>
      
      <%= f.label :Start_date %>
      <%= f.date_field :start_date, class: 'form-control' %>
      
      <%= f.label :End_date %>
      <%= f.date_field :end_date, class: 'form-control' %>
      
      <%= f.label :status %>
      <%= f.select :status, options_for_select(['Active', 'Inactive']) %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>


  </div>
</div>

app/views/courses/index.html.erb
<% provide(:title, 'All courses') %>
<h1>All courses</h1>

<%= will_paginate %>

<ul class="courses">
      <%= render @courses %>
</ul>

<%= will_paginate %>

app/views/courses/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Create Course</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@course) do |f| %>
      <%= render 'shared/course_error_messages' %>

      <%= f.label :course_number %>
      <%= f.text_field :course_number, class: 'form-control' %>

      <%= f.label :Title %>
      <%= f.text_field :title, class: 'form-control' %>

      <%= f.label :Description %>
      <%= f.text_field :description, class: 'form-control' %>

      <%= f.label :Instructor %>
      <%= select_tag :instructor, options_from_collection_for_select(Instructor.all, 'id', 'name')%>
      
      <%= f.label :Start_date %>
      <%= f.date_field :start_date, class: 'form-control' %>
      
      <%= f.label :End_date %>
      <%= f.date_field :end_date, class: 'form-control' %>
      
      <%= f.label :status %>
      <%= f.select :status, options_for_select(['Active', 'Inactive']) %>

      <%= f.submit "Create course", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/courses/search.html.erb
<% provide(:title, "Search course") %>
<h1>Search course</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@course) do |f| %>
      <%= render 'shared/student_error_messages' %>

      <%= f.label :course_number %>
      <%= f.text_field :course_number, class: 'form-control' %>

      <%= f.label :Title %>
      <%= f.text_field :title, class: 'form-control' %>

      <%= f.label :Description %>
      <%= f.text_field :description, class: 'form-control' %>

      <%= f.label :Instructor %>
      <%= f.text_field :instructor, class: 'form-control' %>
      
      <%= f.label :Status %>
      <%= f.text_field :status, class: 'form-control' %>

      <%= f.submit "Search!", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

<%= will_paginate %>

<ul class="courses">
      <%= render @courses %>
</ul>

<%= will_paginate %>

app/views/courses/show.html.erb
<% provide(:title, @course.course_number) %>
<div class="row">

    <section class="course_info">
        
      <h1><%= @course.course_number %></h1>
      
      <h2>Title: <%= @course.title %></h2>
      
      <h2>Description: <%= @course.description %></h2>
      
      <h2>Start_date: <%= @course.start_date %></h2>
      
      <h2>End_date: <%= @course.end_date %></h2>
      
      <h2>Status: <%= @course.status %></h2>
      
      <%if @course.status == "Active" %>
        <h2><%= link_to "edit", edit_course_path(@course), class: "btn btn-primary" %>  <%= link_to "delete", @course, method: :delete, data: { confirm: "You sure?" }, class: "btn btn-primary" %></h2>
      <% else %>
        <h2><%= link_to "delete", @course, method: :delete, data: { confirm: "You sure?" }, class: "btn btn-primary" %></h2>
      <% end %>

    
    </section>
    
</div>

<hr style="height:1px;border:none;border-top:1px solid #555555;" />

<div>
  <h1> Enrolled stuents </h1>
  
  <% @enrollments = Enrollment.all%>
  <% @enrollments.each do |enrollment| %>
    <% if enrollment.course_number == @course.course_number %>
      <% @student = Student.find_by(email: enrollment.student_email) %>
      <% if @student != nil %>
          <li>
              <%=@student.name%>-----
              <%= enrollment.student_email %>----
              <%if enrollment.grade == nil %>
                 no grade 
              <% else %>
                 grade: <%= enrollment.grade %>
              <% end %>
              <%if @course.status == "Active" %>
              | <%= link_to "grade", admin_grade_path(enrollment_id: enrollment.id) %>
              | <%= link_to "drop", drop_student_path(request_id: enrollment.id) %>
              <% end %>
          </li>
      <% end %>
    <% end %>
  <% end %>
  
  <%if @course.status == "Active" %>
  <div class="row">
  <div class="col-md-3 col-md-offset-0">
  <%= form_tag({ controller: 'courses', action: 'add_student' }, method: 'get') do %>
     <label>Add student to this course</label>
    <%= select_tag 'student', options_from_collection_for_select(Student.all, 'id', 'name') %>
    <%= hidden_field_tag :course_id, @course.id %> 
    <%= submit_tag "Add student to course", class: "btn btn-primary" %>
  <% end %>
  </div>
  </div>
  <% end %>

</div>

<hr style="height:1px;border:none;border-top:1px solid #555555;" />

<div>
  <h1> Course Instructor </h1>
  
  <% @courseinstructors = CourseInstructor.all%>
  <% @courseinstructors.each do |instructor| %>
  <% if instructor.course_number == @course.course_number %>
    <li>
      <% @instruct = Instructor.find_by(email: instructor.instructor_email) %>
      <%= @instruct.name %>-----
      <%= instructor.instructor_email %>
      <%if @course.status == "Active" %>
      | <%= link_to "drop", drop_instructor_path(request_id: instructor.id)%>
      <% end %>
    </li>
     <%end%>
  <% end %>
  
  <%if @course.status == "Active" %>
  <div class="row">
  <div class="col-md-3 col-md-offset-0">
  <%= form_tag({ controller: 'courses', action: 'add_instructor' }, method: 'get') do %>
     <label>Add instructor to this course</label>
    <%= select_tag 'instructor', options_from_collection_for_select(Instructor.all, 'id', 'name') %>
    <%= hidden_field_tag :course_id, @course.id %>
    <%= submit_tag "Add instructor to course", class: "btn btn-primary" %>
  <% end %>
  </div>
  </div>
  <% end %>
  
</div>

<hr style="height:1px;border:none;border-top:1px solid #555555;" />

<h1> Materials </h1>


<% @materials = CourseMaterial.where(course_number: @course.course_number ) %>
<% @materials.each do |m| %>
    <div class="row">
        <li>
            <%= m.material%>
        </li>
    </div>
    <hr style=" height:2px;border:none;border-top:2px dotted #185598;" />
<% end %>

<div class="row">

  <%if @course.status == "Active" %>
      <%= form_tag({ controller: 'admins', action: 'addmaterial' }, method: 'get') do %>
        <%= label_tag(:q, "Material") %>
        <%= text_area_tag( :material) %>
        <%= hidden_field_tag :course_number, @course.course_number %>
        <%= submit_tag "Add material", class: "btn btn-primary" %>
      <% end %>
  <% end %>
  
</div>